-- CREACIÓN DEL USUARIO
CREATE USER TEMA_02_PRACTICA_01_AD IDENTIFIED BY TEMA_02_PRACTICA_01_AD;
GRANT DBA TO TEMA_02_PRACTICA_01_AD;

-- CREACIÓN DE LAS TABLAS


-- CREACIÓN DE PK'S


-- CREACIÓN DE FK'S


-- CREACIÓN DE CONSTRAINTS


--INSERCIÓN DE REGISTROS